# Generated by Django 3.0.7 on 2023-12-01 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salebill',
            name='gstin',
        ),
        migrations.AddField(
            model_name='salebill',
            name='emp_code',
            field=models.IntegerField(default=0),
        ),
    ]
